version: 1.2
workflows:
   - name: "SHARE-seq-atac-processing"
     subclass: WDL
     primaryDescriptorPath: /tasks/subwf-atac-single-organism.wdl
     filters:  # All tags, no branches
         branches:
             - main
         tags:
             - /.*/
   - name: "SHARE-seq-atac-processing-dev"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf-atac-single-organism.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - dev
         tags:
             - /.*/

   - name: "SHARE-seq-rna-processing-dev"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf-rna-single-organism.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - dev
         tags:
             - /.*/

   - name: "dorcs-find-dorcs-dev"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf-find-dorcs.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - dev
         tags:
             - /.*/
