version: 1.2
workflows:
   - name: "Combinomics"
     subclass: WDL
     primaryDescriptorPath: /combinomics.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - v2.0.0
             - dev
             - snapatac-chromap-new-parameters
             - IGVF-variant-jamboree
         tags:
             - /.*/

   - name: "Combinomics-peak-to-gene"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf-find-dorcs.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - dev
             - v2.0.0
         tags:
             - /.*/

   - name: "Combinomics-fastqc"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf-fastqc.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - v2.0.0
             - main
             - dev
         tags:
             - /.*/

