version: 1.2
workflows:
   - name: "SHARE-seq"
     subclass: WDL
     primaryDescriptorPath: /share-seq.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
             - release
             - neva
             - minimal-inputs
             - dynamic-memory
             - knudson
             - insert_size_hist
             - barcode_plot_annotations
             - trim-fastqs-atac
             - atac-refactoring
             - main-rebase
         tags:
             - /.*/

   - name: "SHARE-seq-atac-processing"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf-atac-single-organism.wdl
     filters:  # All tags, no branches
         branches:
             - main
             - dev
             - knudson
             - neva
         tags:
             - /.*/

   - name: "SHARE-seq-rna-processing"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf-rna-single-organism.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
             - dev
             - neva
             - knudson
         tags:
             - /.*/

   - name: "dorcs-find-dorcs"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf-find-dorcs.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
             - dev
             - neva
         tags:
             - /.*/

   - name: "SHARE-seq-atac-archr"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf-atac-archr.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
             - dev
             - neva
         tags:
             - /.*/

   - name: "SHARE-seq-rna-seurat"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf-rna-seurat.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
             - dev
             - neva
         tags:
             - /.*/

   - name: "SHARE-seq-sample-demultiplexing"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf-preprocess.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
             - dev
             - neva
             - kdong
         tags:
             - /.*/

   - name: "SHARE-seq-rna-starsolo"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf-rna-starsolo.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
             - dev
             - starsolo
         tags:
             - /.*/
