version: 1.2
workflows:
   - name: "SHARE-seq"
     subclass: WDL
     primaryDescriptorPath: /share-seq.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
         tags:
             - /.*/

   - name: "dorcs-find-dorcs"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf-find-dorcs.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
         tags:
             - /.*/
   - name: "SHARE-seq-atac-archr"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf-atac-archr.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
             - dev
         tags:
             - /.*/

   - name: "SHARE-seq-rna-seurat"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf-rna-seurat.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
             - dev
         tags:
             - /.*/

   - name: "SHARE-seq-sample-demultiplexing"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf-preprocess.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
         tags:
             - /.*/
