version: 1.2
workflows:
   - name: "SHARE-seq ATAC processing"
     subclass: WDL
     primaryDescriptorPath: /tasks/subwf-atac-single-organism.wdl
     filters:  # All tags, no branches
         branches:
             - main
         tags:
             - /.*/
   - name: "SHARE-seq ATAC processing DEV"
     subclass: WDL
     primaryDescriptorPath: /tasks/subwf-atac-single-organism.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - dev
         tags:
             - /.*/

