version: 1.2
workflows:
   - name: "Combinomics"
     subclass: WDL
     primaryDescriptorPath: /share-seq.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
            - main
            - rc-v0.0.1
         tags:
            - /.*/

   - name: "Combinomics-peak-to-gene"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf-find-dorcs.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
            - main
            - rc-v0.0.1
         tags:
            - /.*/

   - name: "Combinomics-atac-archr"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf-atac-archr.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
            - main
            - rc-v0.0.1

         tags:
            - /.*/

   - name: "Combinomics-rna-seurat"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf-rna-seurat.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
            - main
            - rc-v0.0.1
         tags:
            - /.*/

   - name: "Combinomics-sample-demultiplexing"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf-preprocess.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
            - main
            - rc-v0.0.1
         tags:
            - /.*/
