substitutions:
    _DELETION_POLICY: delete
    _REPO_OWNER: broadinstitute
    _GCR_REGISTRY: us.gcr.io
    _BUCKETS_REGION: us-east1

steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'task-correct-fastq'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_correct_fastq:main',
          '-f',
          'dockerfiles/share_task_correct_fastq.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

- name: 'gcr.io/cloud-builders/docker'
  id: 'task-merge-bams'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_merge_bams:main',
          '-f',
          'dockerfiles/share_task_merge_bams.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

- name: 'gcr.io/cloud-builders/docker'
  id: 'task-archr'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_archr:main',
          '-f',
          'dockerfiles/share_task_archr.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

- name: 'gcr.io/cloud-builders/docker'
  id: 'task-10x-preprocess'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/10x_task_preprocess:main',
          '-f',
          'dockerfiles/10x_task_preprocess.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

- name: 'gcr.io/cloud-builders/docker'
  id: 'task-filter-atac'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_filter_atac:main',
          '-f',
          'dockerfiles/share_task_filter_atac.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

- name: 'gcr.io/cloud-builders/docker'
  id: 'task-trim-fastqs-atac'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_trim_fastqs_atac:main',
          '-f',
          'dockerfiles/share_task_trim_fastqs_atac.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

- name: 'gcr.io/cloud-builders/docker'
  id: 'task-bowtie2'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_bowtie2:main',
          '-f',
          'dockerfiles/share_task_bowtie2.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

- name: 'gcr.io/cloud-builders/docker'
  id: 'task-generate-h5'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_generate_h5:main',
          '-f',
          'dockerfiles/share_task_generate_h5.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

- name: 'gcr.io/cloud-builders/docker'
  id: 'task-html-report'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_html_report:main',
          '-f',
          'dockerfiles/share_task_html_report.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

- name: 'gcr.io/cloud-builders/docker'
  id: 'task-joint-qc'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_joint_qc:main',
          '-f',
          'dockerfiles/share_task_joint_qc.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

- name: 'gcr.io/cloud-builders/docker'
  id: 'task-preprocess'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_preprocess:main',
          '-f',
          'dockerfiles/share_task_preprocess.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

- name: 'gcr.io/cloud-builders/docker'
  id: 'task-qc-atac'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_qc_atac:main',
          '-f',
          'dockerfiles/share_task_qc_atac.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

- name: 'gcr.io/cloud-builders/docker'
  id: 'task-qc-rna'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_qc_rna:main',
          '-f',
          'dockerfiles/share_task_qc_rna.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

- name: 'gcr.io/cloud-builders/docker'
  id: 'task-seurat'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_seurat:main',
          '-f',
          'dockerfiles/share_task_seurat.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

- name: 'gcr.io/cloud-builders/docker'
  id: 'task-star'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_star:main',
          '-f',
          'dockerfiles/share_task_star.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

- name: 'gcr.io/cloud-builders/docker'
  id: 'task-find-dorcs'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/dorcs_task_find_dorcs:main',
          '-f',
          'dockerfiles/dorcs_task_find_dorcs.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

# Docker Push

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_correct_fastq:main']
  waitFor: ['task-correct-fastq']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_merge_bams:main']
  waitFor: ['task-merge-bams']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_archr:main']
  waitFor: ['task-archr']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/10x_task_preprocess:main']
  waitFor: ['task-10x-preprocess']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_trim_fastqs_atac:main']
  waitFor: ['task-trim-fastqs-atac']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_filter_atac:main']
  waitFor: ['task-filter-atac']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_bowtie2:main']
  waitFor: ['task-bowtie2']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_generate_h5:main']
  waitFor: ['task-generate-h5']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_html_report:main']
  waitFor: ['task-html-report']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_joint_qc:main']
  waitFor: ['task-joint-qc']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_preprocess:main']
  waitFor: ['task-preprocess']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_qc_atac:main']
  waitFor: ['task-qc-atac']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_qc_rna:main']
  waitFor: ['task-qc-rna']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_seurat:main']
  waitFor: ['task-seurat']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_star:main']
  waitFor: ['task-star']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/dorcs_task_find_dorcs:main']
  waitFor: ['task-find-dorcs']

timeout: 28800s
options:
  machineType: 'E2_HIGHCPU_8'
