substitutions:
    _DELETION_POLICY: delete
    _REPO_OWNER: broadinstitute
    _GCR_REGISTRY: us.gcr.io
    _BUCKETS_REGION: us-east1

steps:
- name: '${_GCR_REGISTRY}/broad-epi-igvf-multiomics-pipeline/share_task_bam2bed'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/broad-epi-igvf-multiomics-pipeline/share_task_bam2bed:latest',
          '-f',
          'dockerfiles/share_task_bam2bed.dockerfile'
          '.' ]
# Docker Push
- name: '${_GCR_REGISTRY}/broad-epi-igvf-multiomics-pipeline/share_task_bam2bed'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/broad-epi-igvf-multiomics-pipeline/share_task_bam2bed:latest']
