substitutions:
    _DELETION_POLICY: delete
    _REPO_OWNER: broadinstitute
    _GCR_REGISTRY: us.gcr.io
    _BUCKETS_REGION: us-east1

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_bam2bed:latest',
          '-f',
          'dockerfiles/share_task_bam2bed.dockerfile',
          '.' ]
  timeout: 5400s
# Docker Push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_bam2bed:latest']
