substitutions:
    _DELETION_POLICY: delete
    _REPO_OWNER: broadinstitute
    _GCR_REGISTRY: us.gcr.io
    _BUCKETS_REGION: us-east1

steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'task-archr'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_archr:v0.0.1',
          '-f',
          'dockerfiles/share_task_archr.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

- name: 'gcr.io/cloud-builders/docker'
  id: 'task-bam2bed'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_bam2bed:v0.0.1',
          '-f',
          'dockerfiles/share_task_bam2bed.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

- name: 'gcr.io/cloud-builders/docker'
  id: 'task-bowtie2'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_bowtie2:v0.0.1',
          '-f',
          'dockerfiles/share_task_bowtie2.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

- name: 'gcr.io/cloud-builders/docker'
  id: 'task-count-atac'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_count_atac:v0.0.1',
          '-f',
          'dockerfiles/share_task_count_atac.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

- name: 'gcr.io/cloud-builders/docker'
  id: 'task-count-rna'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_count_rna:v0.0.1',
          '-f',
          'dockerfiles/share_task_count_rna.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

- name: 'gcr.io/cloud-builders/docker'
  id: 'task-generate-h5'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_generate_h5:v0.0.1',
          '-f',
          'dockerfiles/share_task_generate_h5.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

- name: 'gcr.io/cloud-builders/docker'
  id: 'task-group-umi'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_group_umi:v0.0.1',
          '-f',
          'dockerfiles/share_task_group_umi.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

- name: 'gcr.io/cloud-builders/docker'
  id: 'task-html-report'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_html_report:v0.0.1',
          '-f',
          'dockerfiles/share_task_html_report.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

- name: 'gcr.io/cloud-builders/docker'
  id: 'task-joint-cell-calling'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_joint_cell_calling:v0.0.1',
          '-f',
          'dockerfiles/share_task_joint_cell_calling.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

- name: 'gcr.io/cloud-builders/docker'
  id: 'task-preprocess'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_preprocess:v0.0.1',
          '-f',
          'dockerfiles/share_task_preprocess.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

- name: 'gcr.io/cloud-builders/docker'
  id: 'task-qc-atac'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_qc_atac:v0.0.1',
          '-f',
          'dockerfiles/share_task_qc_atac.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

- name: 'gcr.io/cloud-builders/docker'
  id: 'task-qc-library'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_qc_library:v0.0.1',
          '-f',
          'dockerfiles/share_task_qc_library.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

- name: 'gcr.io/cloud-builders/docker'
  id: 'task-qc-rna'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_qc_rna:v0.0.1',
          '-f',
          'dockerfiles/share_task_qc_rna.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

- name: 'gcr.io/cloud-builders/docker'
  id: 'task-seurat'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_seurat:v0.0.1',
          '-f',
          'dockerfiles/share_task_seurat.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

- name: 'gcr.io/cloud-builders/docker'
  id: 'task-star'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_star:v0.0.1',
          '-f',
          'dockerfiles/share_task_star.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

- name: 'gcr.io/cloud-builders/docker'
  id: 'task-update-rgid'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_update_rgid:v0.0.1',
          '-f',
          'dockerfiles/share_task_update_rgid.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

- name: 'gcr.io/cloud-builders/docker'
  id: 'task-find-dorcs'
  args: [ 'build', '-t',
          '${_GCR_REGISTRY}/${PROJECT_ID}/dorcs_task_find_dorcs:v0.0.1',
          '-f',
          'dockerfiles/dorcs_task_find_dorcs.dockerfile',
          '.' ]
  waitFor: ['-']
  timeout: 28800s

# Docker Push

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_archr:v0.0.1']
  waitFor: ['task-archr']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_bam2bed:v0.0.1']
  waitFor: ['task-bam2bed']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_bowtie2:v0.0.1']
  waitFor: ['task-bowtie2']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_count_atac:v0.0.1']
  waitFor: ['task-count-atac']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_count_rna:v0.0.1']
  waitFor: ['task-count-rna']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_generate_h5:v0.0.1']
  waitFor: ['task-generate-h5']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_group_umi:v0.0.1']
  waitFor: ['task-group-umi']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_html_report:v0.0.1']
  waitFor: ['task-html-report']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_joint_cell_calling:v0.0.1']
  waitFor: ['task-joint-cell-calling']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_preprocess:v0.0.1']
  waitFor: ['task-preprocess']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_qc_atac:v0.0.1']
  waitFor: ['task-qc-atac']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_qc_library:v0.0.1']
  waitFor: ['task-qc-library']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_qc_rna:v0.0.1']
  waitFor: ['task-qc-rna']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_seurat:v0.0.1']
  waitFor: ['task-seurat']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_star:v0.0.1']
  waitFor: ['task-star']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/share_task_update_rgid:v0.0.1']
  waitFor: ['task-update-rgid']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         '${_GCR_REGISTRY}/${PROJECT_ID}/dorcs_task_find_dorcs:v0.0.1']
  waitFor: ['task-find-dorcs']

timeout: 28800s
options:
  machineType: 'E2_HIGHCPU_8'
