---
Project1:
    Name: mouse.skin.trial60.atac
    Primer:
        - P1.04
        - P1.05
        - P1.06
        - P1.07
        - P1.08
    Type: ATAC
Project2:
    Name: mouse.skin.trial60.rna
    Primer:
        - P1.52
        - P1.53
        - P1.54
        - P1.55
        - P1.56
    Type: RNA
...
