[project]
name = "atac-quality-metrics-generation"
version = "1.0.0"
description = "QC scATAC library from fragment file"
requires-python = "==3.10.15"
dependencies = [
    "click==8.1.8",
    "matplotlib==3.10.1",
    "numpy==1.26.4",
    "numba==0.61.0",
    "snapatac2==2.8.0",
    "umap-learn==0.5.7",
    "absl-py==2.1.0",
    "aiohappyeyeballs==2.6.1",
    "aiohttp==3.11.14",
    "aiosignal==1.3.2",
    "altair==5.5.0",
    "anndata==0.10.9",
    "annoy==1.17.3",
    "anyio==4.9.0",
    "array_api_compat==1.11.2",
    "astroid==3.3.9",
    "attrs==25.3.0",
    "cachetools==5.5.2",
    "certifi==2025.1.31",
    "charset-normalizer==3.4.1",
    "chex==0.1.89",
    "contourpy==1.3.1",
    "cycler==0.12.1",
    "cykhash==2.0.1",
    "decorator==5.2.1",
    "Deprecated==1.2.18",
    "dill==0.3.9",
    "docrep==0.3.2",
    "docutils==0.21.2",
    "etils==1.12.2",
    "fbpca==1.0",
    "filelock==3.18.0",
    "firecloud==0.16.37",
    "flax==0.10.4",
    "fonttools==4.56.0",
    "frozenlist==1.5.0",
    "fsspec==2025.3.0",
    "future==1.0.0",
    "geosketch==1.3",
    "google-api-core==2.24.2",
    "google-auth==2.38.0",
    "google-cloud-core==2.4.3",
    "google-cloud-storage==3.1.0",
    "google-crc32c==1.7.0",
    "google-resumable-media==2.7.2",
    "googleapis-common-protos==1.69.2",
    "graphtools==1.5.3",
    "grpcio==1.71.0",
    "h11==0.14.0",
    "h5py==3.13.0",
    "harmonypy==0.0.10",
    "hmmlearn==0.3.3",
    "httplib2==0.22.0",
    "humanize==4.12.1",
    "idna==3.10",
    "igraph==0.11.8",
    "importlib_metadata==8.6.1",
    "importlib_resources==6.5.2",
    "intervaltree==3.1.0",
    "isort==6.0.1",
    "itsdangerous==2.2.0",
    "jax==0.4.38",
    "jaxlib==0.4.38",
    "jedi==0.19.2",
    "Jinja2==3.1.6",
    "joblib==1.4.2",
    "jsonschema==4.23.0",
    "jsonschema-specifications==2024.10.1",
    "kaleido==0.2.1",
    "kiwisolver==1.4.8",
    "legacy-api-wrap==1.4.1",
    "lightning==2.5.1",
    "lightning-utilities==0.14.2",
    "llvmlite==0.44.0",
    "MACS3==3.0.3",
    "magic-impute==3.0.0",
    "marimo==0.11.23",
    "Markdown==3.7",
    "markdown-it-py==3.0.0",
    "MarkupSafe==3.0.2",
    "mccabe==0.7.0",
    "mdurl==0.1.2",
    "ml_collections==1.0.0",
    "ml_dtypes==0.5.1",
    "mpmath==1.3.0",
    "msgpack==1.1.0",
    "mudata==0.3.1",
    "multidict==6.2.0",
    "multipledispatch==1.0.0",
    "multiprocess==0.70.17",
    "narwhals==1.31.0",
    "natsort==8.4.0",
    "nest-asyncio==1.6.0",
    "networkx==3.4.2",
    "nose==1.3.7",
    "numpyro==0.18.0",
    "oauth2client==4.1.3",
    "opt_einsum==3.4.0",
    "optax==0.2.4",
    "orbax-checkpoint==0.11.5",
    "packaging==24.2",
    "pandas==2.0.3",
    "parso==0.8.4",
    "patsy==1.0.1",
    "pillow==11.1.0",
    "platformdirs==4.3.7",
    "plotly==5.24.1",
    "polars==1.25.2",
    "pooch==1.8.2",
    "propcache==0.3.0",
    "proto-plus==1.26.1",
    "protobuf==6.30.1",
    "psutil==7.0.0",
    "pyarrow==19.0.1",
    "pyasn1==0.6.1",
    "pyasn1_modules==0.4.1",
    "pycrdt==0.11.1",
    "pydot==3.0.4",
    "pyfaidx==0.7.2.2",
    "Pygments==2.19.1",
    "PyGSP==0.5.1",
    "pylint==3.3.6",
    "pymdown-extensions==10.14.3",
    "pynndescent==0.5.13",
    "pyparsing==3.2.1",
    "pyro-api==0.1.2",
    "pyro-ppl==1.9.1",
    "python-dateutil==2.9.0.post0",
    "pytorch-lightning==2.5.1",
    "pytz==2025.1",
    "PyYAML==6.0.2",
    "referencing==0.36.2",
    "requests==2.32.3",
    "rich==13.9.4",
    "rpds-py==0.23.1",
    "rsa==4.9",
    "ruff==0.11.1",
    "rustworkx==0.16.0",
    "scanorama==1.7.4",
    "scanpy==1.11.0",
    "scikit-learn==1.5.2",
    "scikit-misc==0.5.1",
    "scipy==1.15.2",
    "scprep==1.2.3",
    "scvi-tools==1.2.1",
    "seaborn==0.13.2",
    "session-info2==0.1.2",
    "setuptools==77.0.3",
    "simplejson==3.20.1",
    "six==1.17.0",
    "sniffio==1.3.1",
    "sortedcontainers==2.4.0",
    "sparse==0.15.5",
    "starlette==0.46.1",
    "statsmodels==0.14.4",
    "sympy==1.13.3",
    "tasklogger==1.2.0",
    "tenacity==9.0.0",
    "tensorboard==2.19.0",
    "tensorboard-data-server==0.7.2",
    "tensorstore==0.1.72",
    "texttable==1.7.0",
    "threadpoolctl==3.6.0",
    "tomlkit==0.13.2",
    "toolz==1.0.0",
    "torch==2.2.2",
    "torchmetrics==1.6.3",
    "tqdm==4.67.1",
    "treescope==0.1.9",
    "typeguard==4.4.2",
    "typing_extensions==4.12.2",
    "tzdata==2025.1",
    "urllib3==2.3.0",
    "uvicorn==0.34.0",
    "websockets==15.0.1",
    "Werkzeug==3.1.3",
    "wrapt==1.17.2",
    "xarray==2024.7.0",
    "xgboost==3.0.0",
    "yarl==1.18.3",
    "zipp==3.21.0",
]

[project.scripts]
qc_atac = "qc_atac:main"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "snapatac2"